import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { AccessPerformanceCommitmentService } from '../src/domain.mjs';
import { AtomicStore } from '../src/store.mjs';

class MemoryStore { constructor() { this.database = { accessPerformanceCommitmentReviews: [] }; this.writes = 0; } read() { return structuredClone(this.database); } write(data) { this.database = structuredClone(data); this.writes += 1; } }
const owner = { id: 'owner-849', role: 'evidence_owner' };
const input = { supplierId: 'SUP-849', evidenceReference: 'EVD-849', commitmentReference: 'CMT-849-ACCESS-01', commitmentScope: 'access_entitlement_commitment' };
const chain = [{ action: 'profileCommitment', role: 'commitment_profile_analyst' }, { action: 'verifyAvailability', role: 'commitment_availability_verifier' }, { action: 'validateCapacity', role: 'commitment_capacity_validator' }, { action: 'authorizeCommitment', role: 'commitment_authority' }, { action: 'releaseCommitment', role: 'commitment_registrar' }];

describe('AccessPerformanceCommitmentService', () => {
  it('records the complete independently controlled commitment lifecycle', () => { const store = new MemoryStore(); const service = new AccessPerformanceCommitmentService(store); let record = service.submit(input, owner, 'request-submit-849'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `request-${step.action}-849`); expect(record.status).toBe('commitment_released'); expect(record.events.map((event) => event.type)).toContain('commitment_released'); expect(store.writes).toBe(6); });
  it('rejects invalid input and invalid role or order without mutation', () => { const store = new MemoryStore(); const service = new AccessPerformanceCommitmentService(store); expect(() => service.submit({ ...input, commitmentScope: 'other' }, owner, 'request-invalid-849')).toThrow('commitment scope is invalid'); const record = service.submit(input, owner, 'request-state-849'); expect(() => service.transition(record.id, 'profileCommitment', { note: 'attempt' }, owner, 'request-role-849')).toThrow('role commitment_profile_analyst is required'); expect(() => service.transition(record.id, 'validateCapacity', { note: 'order' }, { id: 'validator', role: 'commitment_capacity_validator' }, 'request-order-849')).toThrow('access-performance commitment review must be availability_verified'); expect(store.writes).toBe(1); });
  it('rejects duplicate requests, missing records, and terminal transitions', () => { const store = new MemoryStore(); const service = new AccessPerformanceCommitmentService(store); let record = service.submit(input, owner, 'request-repeat-849'); expect(() => service.transition(record.id, 'profileCommitment', { note: 'repeat' }, { id: 'profile', role: 'commitment_profile_analyst' }, 'request-repeat-849')).toThrow('request identifier was already used'); expect(() => service.get('missing-849')).toThrow('access-performance commitment review was not found'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `terminal-${step.action}-849`); expect(() => service.transition(record.id, 'releaseCommitment', { note: 'retry' }, { id: 'registrar', role: 'commitment_registrar' }, 'retry-release-849')).toThrow('access-performance commitment review must be commitment_authorized'); });
  it('recovers an absent commitment data file', () => { const directory = mkdtempSync(join(tmpdir(), 'access-performance-commitment-')); try { const store = new AtomicStore(join(directory, 'data', 'access-performance-commitment-reviews.json')); expect(store.read()).toEqual({ accessPerformanceCommitmentReviews: [] }); } finally { rmSync(directory, { recursive: true, force: true }); } });
});
